# Travis CI configuration
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install -r requirements.txt
  - "python -m nltk.downloader stopwords"
  - "python -m nltk.downloader wordnet"
  - "python -m spacy download en"
   

# command to run tests
script: pytest --doctest-modules

ignore:
  - mallet-2.0.8
  - Part_2_1_1_combined_dataset_topic_modeling.py
