# Travis CI configuration
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7


install:
  - pip install -r requirements.txt
  - "python -m nltk.downloader stopwords"
  - "python -m nltk.downloader wordnet"
  - "python -m spacy download en"
   

# command to run tests
script: pytest --doctest-modules Part_1_Data_preprocessing.py Part_2_0_Analytics_bow_approach.py Part_2_1_2_create_input4cclda.py Part_2_3_sentiment_analysis.py

