# Travis CI configuration
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install -r requirements.txt
  - "python -m nltk.downloader stopwords"
  - "python -m nltk.downloader wordnet"
  - "python -m spacy download en"
   

# command to run tests
before_script:
  rm ./mallet-2.0.8;
  wget http://mallet.cs.umass.edu/dist/mallet-2.0.8.zip -O file.zip; unzip file.zip; rm file.zip;
  chmod +x ./mallet-2.0.8
script: pytest --doctest-modules
