# Travis CI configuration
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7

install:
  - pip install -r requirements.txt
  - "python -m nltk.downloader stopwords"
  - "python -m nltk.downloader wordnet"
  - "python -m spacy download en"
   

# command to run tests
if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep 'Part_2_1_1_combined_dataset_topic_modeling.py'
then
  echo "Only docs were updated, not running the CI."
  exit
script: pytest --doctest-modules
